### PR TITLE
🤓 Some benchmarks.

### PR DESCRIPTION
**Pull request by aichholzer**
It is, perhaps, a good idea to have some basic benchmarks and also an option for people to run them as well. 👍

### CODE REVIEW

**Comment by aichholzer** [comment]
Maybe something to consider: https://github.com/fastify/benchmarks/pull/47
> Basically autocannon would become the bottleneck to benchmark turbo-http.

**Comment by aichholzer** [comment]
@mafintosh -Has this stalled?

**Comment by mafintosh** [comment]
Sorry I missed this. Great work :)

**Comment by mafintosh** [comment]
You wanna help maintain this in general? I can add you as an owner if you want :)

**Comment by aichholzer** [comment]
@mafintosh -Glad to hear.
Sure, happy to maintain. 👍

**Comment by aichholzer** [comment]
@mafintosh -If you still need my help, I can help go through the `issues` and `pull requests`. Just let me know. 👍

**Comment by aichholzer** [comment]
@mafintosh 
> You wanna help maintain this in general? I can add you as an owner if you want :)

Still need a hand (or two)?

**Pull request merged**
